name: Sarahhines
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.23145973728969693
  lightness: 0.0625
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
